Improve usability of license.py
Removes unused arguments and marks required subparser as required.

Before:
```
✗ python scripts/license.py
Traceback (most recent call last):
  File "/Users/scottgigante/git/ctvc/codecov/scripts/license.py", line 93, in <module>
    main()
  File "/Users/scottgigante/git/ctvc/codecov/scripts/license.py", line 83, in main
    print(pref.command)
          ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'command'
```

After:
```
✗ python scripts/license.py
usage: codecov key gen [-h] {new,check} ...
codecov key gen: error: the following arguments are required: {new,check}
```